---@shape QBItemCombinableData
---@field accept string[] The other item that can be it can be combined with
---@field reward string The item that is rewarded upon successful combine
---@field anim QBItemCombinableDataAnim Set the animation, progressbar text and length of time it takes to combine
